#!/usr/bin/env bash
# Point the frontend at a TVC app URL.
#
# config.js is gitignored, so this runs locally before opening the page and in the
# pages workflow before publishing. Nothing names an enclave in the repo itself.
set -euo pipefail

URL="${TVC_APP_URL:-http://127.0.0.1:44020}"

cat > "$(dirname "$0")/config.js" <<CONFIG
// Generated by build.sh. Do not edit by hand.
window.TVC_APP_URL = '${URL}';
CONFIG

echo "config.js -> ${URL}"
