#!/usr/bin/env bash
# Point the frontend at a TVC app URL. Run this and commit config.js.
set -euo pipefail

URL="${TVC_APP_URL:-http://127.0.0.1:44020}"

cat > "$(dirname "$0")/config.js" <<CONFIG
// Generated by build.sh — do not edit by hand.
window.TVC_APP_URL = '${URL}';
CONFIG

echo "config.js -> ${URL}"
