// Generated by build.sh, and gitignored. This checked-in copy is the local default.
// Run build.sh with TVC_APP_URL set to point the page at a deployed enclave.
window.TVC_APP_URL = 'http://127.0.0.1:44020';
